version: "3"
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 8080:80/tcp
        volumes:
            - .:/var/www
        network_mode: bridge